# Generated by Django 4.2.4 on 2023-10-03 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_biodata_nama'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodata',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='biodata',
            name='nama_belakang',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='biodata',
            name='nama_depan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='telp',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
