# Generated by Django 4.2.4 on 2023-11-28 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_biodata_email_biodata_nama_belakang_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biodata',
            old_name='user',
            new_name='username',
        ),
    ]
