# Generated by Django 4.2.4 on 2023-09-07 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kendaraan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_polisi', models.CharField(max_length=100)),
                ('merk_kendaraan', models.CharField(max_length=100)),
                ('type_kendaraan', models.CharField(max_length=100)),
                ('tahun_kendaraan', models.CharField(max_length=20)),
                ('harga', models.CharField(max_length=50)),
            ],
        ),
    ]
