# Generated by Django 4.2.4 on 2023-09-07 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kendaraan',
            options={'verbose_name_plural': 'kendaraan'},
        ),
        migrations.AddField(
            model_name='kendaraan',
            name='nama',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kendaraan',
            name='harga',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='kendaraan',
            name='merk_kendaraan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kendaraan',
            name='no_polisi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kendaraan',
            name='tahun_kendaraan',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='kendaraan',
            name='type_kendaraan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
