# Generated by Django 4.2.4 on 2023-09-09 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_kendaraan_options_kendaraan_nama_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('create_at', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'ketegori',
            },
        ),
        migrations.AlterModelOptions(
            name='kendaraan',
            options={'verbose_name_plural': 'Kendaraan'},
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_penyewaan', models.CharField(blank=True, max_length=100, null=True)),
                ('tgl_kembali', models.CharField(blank=True, max_length=10, null=True)),
                ('harga', models.CharField(blank=True, max_length=100, null=True)),
                ('total', models.CharField(blank=True, max_length=100, null=True)),
                ('kendaraan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.kendaraan')),
            ],
            options={
                'verbose_name_plural': 'Transaksi',
            },
        ),
        migrations.CreateModel(
            name='MonitoringKendaraan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_polisi', models.CharField(blank=True, max_length=100, null=True)),
                ('km_kendaraan', models.CharField(blank=True, max_length=100, null=True)),
                ('tgl_pemeriksaan_kendaraan', models.CharField(blank=True, max_length=100, null=True)),
                ('tgl_perawatan_kendaraaan', models.CharField(blank=True, max_length=100, null=True)),
                ('kendaraan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.kendaraan')),
            ],
            options={
                'verbose_name_plural': 'MonitoringKendaraan',
            },
        ),
        migrations.AddField(
            model_name='kendaraan',
            name='kategori',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.kategori'),
        ),
    ]
