# Generated by Django 4.2.4 on 2023-09-09 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_kategori_alter_kendaraan_options_transaksi_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kategori',
            options={'verbose_name_plural': 'Kategori'},
        ),
        migrations.RenameField(
            model_name='monitoringkendaraan',
            old_name='tgl_perawatan_kendaraaan',
            new_name='tgl_perawatan_kendaraan',
        ),
        migrations.RemoveField(
            model_name='kategori',
            name='create_at',
        ),
    ]
