# Generated by Django 4.2.4 on 2023-10-10 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_monitoringkendaraan_air_radiator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoringkendaraan',
            name='air_radiator',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='monitoringkendaraan',
            name='air_wiper',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='monitoringkendaraan',
            name='ban',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='monitoringkendaraan',
            name='lampu',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='monitoringkendaraan',
            name='oli',
            field=models.BooleanField(default=False),
        ),
    ]
