# Generated by Django 4.2.4 on 2023-10-10 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_monitoringkendaraan_air_radiator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoringkendaraan',
            name='air_radiator',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='monitoringkendaraan',
            name='air_wiper',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='monitoringkendaraan',
            name='ban',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='monitoringkendaraan',
            name='lampu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='monitoringkendaraan',
            name='oli',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
