# Generated by Django 4.2.4 on 2023-10-14 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_monitoringkendaraan_air_radiator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='tgl_kembali',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='tgl_penyewaan',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
