# Generated by Django 4.2.4 on 2023-10-24 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_transaksi_tgl_kembali_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
