# Generated by Django 4.2.4 on 2023-10-24 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_transaksi_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kendaraan',
            name='harga',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
