# Generated by Django 4.2.4 on 2023-11-15 03:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_transaksi_harga'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metode_pembayaran', models.CharField(blank=True, max_length=100, null=True)),
                ('total_pembayaran', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('transaksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.transaksi')),
            ],
        ),
    ]
