# Generated by Django 4.2.4 on 2023-11-30 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_transaksi_sudah_dikembalikan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True),
        ),
    ]
