# Generated by Django 4.2.4 on 2023-11-30 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_transaksi_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='kendaraan',
            name='status',
            field=models.CharField(choices=[('tersedia', 'Tersedia'), ('disewa', 'Disewa')], default='tersedia', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
