# Generated by Django 4.2.7 on 2023-12-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_kendaraan_status_alter_transaksi_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pembayaran',
            old_name='metode_pembayaran',
            new_name='merchant_ref',
        ),
        migrations.AddField(
            model_name='pembayaran',
            name='method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pembayaran',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pembayaran',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('PAID', 'PAID'), ('EXPIRED', 'EXPIRED')], default='PENDING', max_length=20),
        ),
    ]
